### ISSUE TITLE
Limit

### ISSUE THREAD

**Issue by lars0302** [surenjanath/Spotify-Playlist-Download#1]
Hi, I have a spotify list with 150 songs but their is a limit of 100.
![image](https://user-images.githubusercontent.com/112115036/222992030-2a04a8f0-bbab-4b76-9faf-d2c06d56a82c.png)
and Idk how I can change the limit.
So could you please help me ?

**Comment by surenjanath** [comment]
Hi yes I've solved it, sorry forgot to add the headers to the offset section. You're good to go once again for more than 100 songs
