### ISSUE TITLE
Error Status Code: 'links'

### ISSUE THREAD

**Issue by orty17** [surenjanath/Spotify-Playlist-Download#2]
Hey When I run this script, nearly every Track prints a `Error Status Code: 'links'`... Can you fix this issue or tell me how I can fix this issue?

Futhermore the songs wich can be download are not playable, Can you tell me in this case how I can fix this issue too?

Best wishes :)

**Comment by orty17** [comment]
Side note: the var data wich is filled by the generate_Analyze_id contains while running the following content: {'status': 'ok', 'c_status': 'FAILED', 'mess': 'Sorry! An error has occurred.'}

**Comment by surenjanath** [comment]
Okay so I've added a new fix. Try and let me know. if not  please provide the Playlist.
Thanks
