### ISSUE TITLE
Directory Error

### ISSUE THREAD

**Issue by tazdik-07** [surenjanath/Spotify-Playlist-Download#3]
After entering the link of the playlist, it starts downloading as usual but while downloading a song it shows `Error Status Code :  [Errno 2] No such file or directory: `

As a result no song can be downloaded. Please fix this ASAP.

**Comment by tazdik-07** [comment]
Every single song prints this error
![image](https://user-images.githubusercontent.com/132375410/235707208-63e56db8-870b-4133-93f6-7abe224a8d0d.png)

**Comment by surenjanath** [comment]
Somehow i cannot replicate this error, please put the ipynb file in a separate folder and dont run it from the temp folder if you just open it from the extract file
