### ISSUE TITLE
Playlists throwing "Error Status Code : string indices must be integers, not 'str'" for some songs

### ISSUE THREAD

**Issue by marlonbrito** [surenjanath/Spotify-Playlist-Download#5]
I'm seeing an error in some playlists for some reason:
Error Status Code : string indices must be integers, not 'str'
This error only seems to happen for some songs.
![image](https://github.com/surenjanath/Spotify-Playlist-Download/assets/85363603/860a59c7-dd6d-4713-82ae-b337fa2adc6a)

**Comment by surenjanath** [comment]
Hi I hope this new version works. good luck.
